---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: workflow-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: workflow-controller
    spec:
      containers:
      - name: workflow-controller
        image: {% if DEPLOYMENT == 'prod' %}{{DOCKER_REGISTRY}}/{% endif %}{{WORKFLOW_CONTROLLER_IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        ports:
        - containerPort: 5000
          name: http
