apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fibo-atlas-worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fibo-atlas-worker
    spec:
      containers:
       - name: fibo-atlas-worker
         image: gitlab-registry.cern.ch/rodrigdi/cap-reuse:fibonacci-workflow-controller
         imagePullPolicy: Always
         env:
          - name: QUEUE_ENV
            value: "fibo-atlas-queue"
          - name: EXPERIMENT
            value: "atlas"
          - name: SHARED_VOLUME
            value: "/k8s/atlas"
         volumeMounts:
          - name: atlas-pv
            mountPath: "/data"
      securityContext:
        fsGroup: 0
      volumes:
       - name: atlas-pv
         cephfs:
           monitors:
            - 128.142.36.227:6790
            - 128.142.39.77:6790
            - 128.142.39.144:6790
           path: "/k8s/atlas"
           user: k8s
           secretRef:
             name: ceph-secret
           readOnly: false
